# Generated by Django 5.0.4 on 2024-04-10 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="VideoModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("video", models.FileField(upload_to="videos")),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("detection", models.CharField(max_length=255)),
            ],
        ),
    ]
