volumes:
  data:

services:
  database:
    container_name: database
    image: mysql
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yolo_db

    volumes:
      - data:/var/lib/mysql

  broker:
    container_name: broker
    build:
      context: ./broker
      dockerfile: broker.Dockerfile
    ports:
      - "1883:1883"
      - "9001:9001"

  backend:
    depends_on:
    - database
    container_name: backend
    image: backend
    build:
      context: ../backend/
      dockerfile: ../backend/Dockerfile
    env_file:
      - .env

    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../backend/backend/static_files:/app/backend/static_files

  frontend:
    depends_on:
      - backend
    container_name: frontend
    image: frontend
    build:
      context: ../frontend
      dockerfile: ../frontend/Dockerfile
    restart: always
    ports:
      - "4200:4200"
