volumes:
  data:

services:
  database:
    container_name: database
    image: mysql
    ports:
      - "3308:3306"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: yolo_db

    volumes:
      - data:/var/lib/mysql

  backend:
    depends_on:
    - database
    container_name: backend
    image: backend
    build:
      context: ../backend/
      dockerfile: ../backend/Dockerfile
    env_file:
      - .env

    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ../backend/backend/static_files:/app/backend/static_files
